project:
    create: true
    name: kuwu

applications:
    ################## PATCH OPERATOR #############################
    patchOperator:
        name: patch-operator
        enabled: true
        argoProject: gepaplexx
        destination:
            namespace: openshift-operators
            create: true
        source:
            repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
            chart: gp-patch-operator
            targetRevision: "*"
        syncPolicy:
            automated:
                prune: true
                selfHeal: true



    ##################### CERT-MANAGER ######################
    certManager:
        name: cert-manager
        enabled: true
        argoProject: kuwu
        destination:
            namespace: cert-manager
            create: true
        source:
            repoURL: "https://charts.jetstack.io"
            chart: cert-manager
            targetRevision: "*"
            helm:
                parameters:
                    - cert-manager:
                        installCRDs: true
                        extraArgs:
                            - --dns01-recursive-nameservers-only
                            - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
        syncPolicy:
            automated:
                prune: true
                selfHeal: true





##################### CERTIFICATES-PATCHES ######################
#certificatesPatches:
#    name: certificate-patches
#    enabled: true
#    argoProject: kuwu
#    destination:
#        namespace: kuwu-infrastructure
#        create: true
#    source:
#        repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
#        chart: gp-certificates-patches
#        targetRevision: "*"
#        helm:
#            parameters:
#                - name: "apiserver.customApiUrl"
#                  value: "api.kuwu.uff.cool"
#    syncPolicy:
#        automated:
#            prune: true
#            selfHeal: true
