project:
    create: true
    name: kuwu

applications:
  ####################### Multena Instance ######################
  multena:
    name: multena
    enabled: true
    argoProject: kuwu
    destination:
      namespace: multena
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      targetRevision: "*"
      chart: "gp-multena-instance"
    syncPolicy: {}

    ################## PATCH OPERATOR #############################
  patchOperator:
      name: patch-operator
      enabled: true
      argoProject: kuwu
      destination:
        namespace: openshift-operators
        create: true
      source:
        repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
        chart: gp-patch-operator
        targetRevision: "*"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true


  uff-mc:
    name: uff-mc
    enabled: true
    argoProject: kuwu
    destination:
      namespace: uff-mc
      create: true
    source:
      helm:
        valueFiles:
          - ./values/servers.yaml
      path: .
      repoURL: 'https://github.com/uff-cool/uff-mc'
      targetRevision: HEAD
    syncPolicy:
      automated:
         prune: true
         selfHeal: true

  uff-minio:
    name: uff-minio
    enabled: true
    argoProject: kuwu
    destination:
      namespace: uff-minio
      create: true
    source:
      helm:
        valueFiles:
          - ./values.yaml
      path: .
      repoURL: 'https://github.com/uff-cool/uff-minio'
      targetRevision: HEAD
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
