project:
    create: true
    name: kuwu

applications:
  ####################### Multena Instance ######################
  multena:
    name: multena
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: multena
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      targetRevision: "*"
      chart: "gp-multena-instance"
    syncPolicy: {}
    
    ################## PATCH OPERATOR #############################
  patchOperator:
      name: patch-operator
      enabled: true
      argoProject: kuwu
      destination:
        namespace: openshift-operators
        create: true
      source:
        repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
        chart: gp-patch-operator
        targetRevision: "*"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
                
                
  uff-mc:
    name: uff-mc
    enabled: true
    argoProject: kuwu
    destination:
      namespace: uff-mc
      create: true
    source:
      repoURL: "https://github.com/uff-cool/uff-mc"
      path: .
      targetRevision: HEAD
    syncPolicy:
      automated:
         prune: true
         selfHeal: true



    ##################### CERT-MANAGER ######################
  certManager:
        name: cert-manager
        enabled: true
        argoProject: kuwu
        destination:
            namespace: cert-manager
            create: true
        source:
            repoURL: "https://charts.jetstack.io"
            chart: cert-manager
            targetRevision: "*"
            helm:
                parameters:
                    - cert-manager:
                        installCRDs: true
                        extraArgs:
                            - --dns01-recursive-nameservers-only
                            - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
        syncPolicy:
            automated:
                prune: true
                selfHeal: true





##################### CERTIFICATES-PATCHES ######################
#certificatesPatches:
#    name: certificate-patches
#    enabled: true
#    argoProject: kuwu
#    destination:
#        namespace: kuwu-infrastructure
#        create: true
#    source:
#        repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
#        chart: gp-certificates-patches
#        targetRevision: "*"
#        helm:
#            parameters:
#                - name: "apiserver.customApiUrl"
#                  value: "api.kuwu.uff.cool"
#    syncPolicy:
#        automated:
#            prune: true
#            selfHeal: true
